 steps:
 # Authenticate with Docker
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
   secretEnv: ['USERNAME', 'PASSWORD']
 # Build the Docker image from .devcontainer folder
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: [
     '-c',
     'docker build --build-arg BRANCH_NAME=$$BRANCH_NAME -t $$USERNAME/lind-wasm:latest ./.devcontainer'
   ]
   secretEnv: ['USERNAME'] 
# Run the container and execute the bazel command
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker run -e BRANCH_NAME=$$BRANCH_NAME --rm -v $$PWD:/workspace -w /workspace $$USERNAME/lind-wasm:latest bazel run //:python_tests']
   secretEnv: ['USERNAME']   
# Copy the analysis file from the container to the host
#  - name: 'gcr.io/cloud-builders/docker'
#    entrypoint: 'bash'
#    args: ['-c', 'docker cp $$USERNAME/lind-wasm/src/RawPOSIX/tmp/results.json:/workspace/results.json ./']
#    secretEnv: ['USERNAME']

# Validate the analysis file (Example: Check for errors)
# This is where we will need to put the check to validate results.json

 options:
  logging: CLOUD_LOGGING_ONLY  
  machineType: 'E2_HIGHCPU_8'
 availableSecrets:
   secretManager:
   - versionName: projects/1049119266483/secrets/docker-password/versions/1
     env: 'PASSWORD'
   - versionName: projects/1049119266483/secrets/docker-username/versions/1
     env: 'USERNAME'
