name: End-to-end testing

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build e2e
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          platforms: linux/amd64
